apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-oldcentos
spec:
  selector:
    matchLabels:
      app: centos
  replicas: 1
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: centos:centos6.9
          command:
          - tail
          - -f
          - /dev/null

